config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  # ###Contractor##################################

  # ---contractor/devise関係-------------------
  devise_for :contractors, controllers: {
    sessions: 'contractors/sessions',
    passwords: 'contractors/passwords',
    registrations: 'contractors/registrations',
    confirmations: 'contractors/confirmations'
  }
  devise_scope :contractor do
    # ここのモデル名単数系にする
    post 'contractors/guest_login', to: 'contractors/sessions#guest_login'
  end

  # ---contractors/profiles----------------
  # deviseにより提供されるcurrent_contractorがあるためcontractor_idは不要になる
  # 不要なidをURLに露出させないためにresourcesでなくnamespaceを使う
  # client側でもプロフィールを見るため特定のためidは必要（clientユーザーはcurrent_contractorは使えないので)
  namespace :contractors do
    resource :profile, only: [:show, :edit, :update]
  end

  # ---contractors/request_applications----------------
  # only: []はそのリソースに対するルーティングを意図的に生成しないようにするためのものであり、ネストされたリソースに対するルーティングのみを生成したい
  # 自分が応募した仕事、本人にだけ表示すれば良い
  namespace :contractors do
    resources :request_applications, only: [:index, :create, :destroy]
  end

  # ---contractors/favorites----------------
  namespace :contractors do
    resources :favorites, only: [:index, :create, :destroy]
  end

  # ---contractors/notifications----------------
  namespace :contractors do
    resources :notifications, only: [:index]
  end

  # ###Client##################################

  # ---client/devise関係-------------------
  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    confirmations: 'clients/confirmations'
  }

  devise_scope :client do
    post 'clients/guest_login', to: 'clients/sessions#guest_login'
    # put 'clients/confirmation', to: 'clients/confirmations#show'
  end

  # ---clients/requests----------------------
  # controllers/clients/以下にcontrollerを配置している場合namespaceメソッドでネストするかmodule: :clientsオプションをつける
  # client専用
  namespace :clients do
    resources :requests, only: [:index, :new, :edit, :create, :update, :destroy]
  end

  # 一般公開用(ゲスト、受注者も見るためclients/requestsとは分ける)
  resources :public_requests, only: [:index, :show], controller: 'public_requests'

  # ---clients/profiles----------------------
  namespace :clients do
    resource :profile, only: [:show, :edit, :update]
  end

  # ---clients/applicants--------------------
  namespace :clients do
    resources :applicants, only: [:index, :show]
  end

  # ---clients/engagements--------------------
  namespace :clients do
    resources :engagements, only: [:create, :show, :index]
  end

  # ---contractors/notifications----------------
  namespace :clients do
    resources :notifications, only: [:index]
  end


  # ###その他###############################

  # ---static_pages--------------------------
  root 'static_pages#about'
  get 'about' => 'static_pages#about'
  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'signup' =>  'static_pages#signup'
  get 'login' =>  'static_pages#login'
  get 'guest_login' =>  'static_pages#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ---contacts------------------------------
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      get 'confirm'
      post 'back'
      get 'back'
      get 'done'
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def privacy
  end

  def terms
  end

  def signup
  end

  def login
  end

  def guest_login
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, t('.title')) %>
<div class="bg-center bg-cover text-center pt-40 pb-5 text-white" style="background-image: url('<%= asset_path('hero.jpg') %>');">
  <p class="mb-5 text-6xl drop-shadow-lg"><%= t('.hero_word1') %></p>
  <p class="text-4xl mb-20 drop-shadow-lg"><%= t('.hero_word2') %></p>
  <%= link_to signup_path, class: 'inline-block bg-orange-400 px-5 py-2 rounded-full hover:bg-orange-300 transition w-30' do %>
    <button>
      <%= t('.sign_up_button') %>
    </button>
  <% end %>
</div>
<div class="mx-30">
  <div>
    <p><%= t('.text1') %></p>
    <div>
      <div></div>
      <div></div>
    </div>
  </div>
</div>

app/views/static_pages/guest_login.html.erb
<% provide(:title, t('.title')) %>
<div class="flex justify-center items-center" >
  <div class="w-1/2 py-12 flex justify-between text-center">
  <%= button_to contractors_guest_login_path, class: "w-64 h-64 bg-blue-200 rounded-lg" do %>
    <p class='text-2xl font-bold'><%= t('.contractor') %></p>
    <p class='text-2xl font-bold'><%= t('.login') %></p>
    <p class='text-sm mt-5'><%= t('.contractor_text') %></p>
  <% end %>
  <%= button_to clients_guest_login_path, method: :post, class: "w-64 h-64 bg-red-200 rounded-lg" do %>
    <p class='text-2xl font-bold'><%= t('.client') %></p>
    <p class='text-2xl font-bold'><%= t('.login') %></p>
    <p class='text-sm mt-5'><%= t('.client_text') %></p>
  <% end %>
  </div>
</div>

app/views/static_pages/login.html.erb
<% provide(:title, t('.title')) %>
<div class="flex justify-center items-center" >
  <div class="w-1/2 py-12 flex justify-between text-center">
  <%= link_to new_contractor_session_path, class: "w-64 h-64 bg-blue-200 rounded-lg pt-24" do %>
    <p class='text-2xl font-bold'><%= t('.contractor') %></p>
    <p class='text-sm mt-5'><%= t('.contractor_text') %></p>
  <% end %>
  <%= link_to new_client_session_path, class: "w-64 h-64 bg-red-200 rounded-lg pt-24" do %>
    <p class='text-2xl font-bold'><%= t('.client') %></p>
    <p class='text-sm mt-5'><%= t('.client_text') %></p>
  <% end %>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'プライバシーポリシー') %>
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/signup.html.erb
<% provide(:title, t('.title')) %>
<div class="flex justify-center items-center" >
  <div class="w-1/2 py-12 flex justify-between text-center">
  <%= link_to new_contractor_registration_path, class: "w-64 h-64 bg-blue-200 rounded-lg pt-24" do %>
    <p class='text-2xl font-bold'><%= t('.contractor') %></p>
    <p class='text-sm mt-5'><%= t('.contractor_text') %></p>
  <% end %>
  <%= link_to new_client_registration_path, class: "w-64 h-64 bg-red-200 rounded-lg pt-24" do %>
    <p class='text-2xl font-bold'><%= t('.client') %></p>
    <p class='text-sm mt-5'><%= t('.client_text') %></p>
  <% end %>
  </div>
</div>

app/views/static_pages/signup_type.html.erb
<% provide(:title, '登録ページへ') %>
<%= render 'layouts/devise_user_header' %>
<h2>ご希望のユーザータイプをクリックして下さい。</h1>
<p><%= link_to '受注者登録', new_contractor_registration_path %></p>
<p><%= link_to '発注者登録', new_client_registration_path %></p>

app/views/static_pages/terms.html.erb
<% provide(:title, '利用規約') %>
<h1>StaticPages#terms</h1>
<p>Find me in app/views/static_pages/terms.html.erb</p>