config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  # ###Contractor##################################

  # ---contractor/devise関係-------------------
  devise_for :contractors, controllers: {
    sessions: 'contractors/sessions',
    passwords: 'contractors/passwords',
    registrations: 'contractors/registrations',
    confirmations: 'contractors/confirmations'
  }
  devise_scope :contractor do
    # ここのモデル名単数系にする
    post 'contractors/guest_login', to: 'contractors/sessions#guest_login'
  end

  # ---contractors/profiles----------------
  # deviseにより提供されるcurrent_contractorがあるためcontractor_idは不要になる
  # 不要なidをURLに露出させないためにresourcesでなくnamespaceを使う
  # client側でもプロフィールを見るため特定のためidは必要（clientユーザーはcurrent_contractorは使えないので)
  namespace :contractors do
    resource :profile, only: [:show, :edit, :update]
  end

  # ---contractors/request_applications----------------
  # only: []はそのリソースに対するルーティングを意図的に生成しないようにするためのものであり、ネストされたリソースに対するルーティングのみを生成したい
  # 自分が応募した仕事、本人にだけ表示すれば良い
  namespace :contractors do
    resources :request_applications, only: [:index, :create, :destroy]
  end

  # ---contractors/favorites----------------
  namespace :contractors do
    resources :favorites, only: [:index, :create, :destroy]
  end

  # ---contractors/notifications----------------
  namespace :contractors do
    resources :notifications, only: [:index]
  end

  # ###Client##################################

  # ---client/devise関係-------------------
  devise_for :clients, controllers: {
    sessions: 'clients/sessions',
    passwords: 'clients/passwords',
    registrations: 'clients/registrations',
    confirmations: 'clients/confirmations'
  }

  devise_scope :client do
    post 'clients/guest_login', to: 'clients/sessions#guest_login'
    # put 'clients/confirmation', to: 'clients/confirmations#show'
  end

  # ---clients/requests----------------------
  # controllers/clients/以下にcontrollerを配置している場合namespaceメソッドでネストするかmodule: :clientsオプションをつける
  # client専用
  namespace :clients do
    resources :requests, only: [:index, :new, :edit, :create, :update, :destroy]
  end

  # 一般公開用(ゲスト、受注者も見るためclients/requestsとは分ける)
  resources :public_requests, only: [:index, :show], controller: 'public_requests'

  # ---clients/profiles----------------------
  namespace :clients do
    resource :profile, only: [:show, :edit, :update]
  end

  # ---clients/applicants--------------------
  namespace :clients do
    resources :applicants, only: [:index, :show]
  end

  # ---clients/engagements--------------------
  namespace :clients do
    resources :engagements, only: [:create, :show, :index]
  end

  # ---contractors/notifications----------------
  namespace :clients do
    resources :notifications, only: [:index]
  end


  # ###その他###############################

  # ---static_pages--------------------------
  root 'static_pages#about'
  get 'about' => 'static_pages#about'
  get 'privacy' => 'static_pages#privacy'
  get 'terms' => 'static_pages#terms'
  get 'signup' =>  'static_pages#signup'
  get 'login' =>  'static_pages#login'
  get 'guest_login' =>  'static_pages#guest_login'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ---contacts------------------------------
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      get 'confirm'
      post 'back'
      get 'back'
      get 'done'
    end
  end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_application_button.html.erb
<%# dom_idにより各ボタンに対し一意のidを作成が可能になる %>
<% application_button_id = dom_id(req, :application_button) %>

<turbo-frame id="<%= application_button_id %>">
  <% if current_contractor.request_applications.exists?(request_id: req.id) %>
    <%= form_with url: contractors_request_application_path(current_contractor), method: :delete, data: { turbo_frame: application_button_id }, local: true do |form| %>
      <%= hidden_field_tag :request_id, req.id %>
      <%= form.submit 'キャンセルする', class: 'w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-500 text-base font-medium text-white hover:bg-red-700 focus:outline-none sm:w-auto sm:text-sm' %>
    <% end %>
  <% else %>
    <button data-open-modal="confirmationModal-<%= req.id %>" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-10 rounded focus:outline-none focus:shadow-outline cursor-pointer block">申し込む</button>
  <% end %>
  <%= render 'shared/modal_apply_request', req: req, application_button_id: application_button_id %>
</turbo-frame>

app/views/shared/_back_button.html.erb
<%= link_to '戻る', @back_url || public_requests_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

app/views/shared/_back_to_home.html.erb
<%= link_to 'ホームへ戻る', public_requests_path, class: "inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>

app/views/shared/_confirmations_form_fields.html.erb
<%= form_for(resource, as: resource_name, url: confirmation_path(resource_name), html: { method: :post }) do |f| %>

  <div class="mb-5">
    <%= f.label :email, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.email_field :email, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email), class: form_field_error_class(resource, :email) %>
    <%= display_field_error_messages(resource, :email) %>

  </div>

  <%= f.submit submit, class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer mb-3' %>
<% end %>

app/views/shared/_counts_favorites_applicants.html.erb
<div class="flex justify-end gap-6 text-sm text-gray-500">
  <% if current_client && req.client == current_client %>
    <p class="pl-4">
      現在の応募者数　：
      <%= link_to clients_applicants_path(request_id: req.id) do %>
        <span class="font-semibold text-blue-700"><%= req.applicants.count %></span>
        名
        <span class="font-semibold text-blue-700">（応募者一覧）</span>
      <% end %>
    </p>
  <% else %>
    <p class="pl-4">
      現在の応募者数　：
      <span class="font-semibold text-cyan-500"><%= req.applicants.count %></span>
      名
    </p>
  <% end %>
  <p class="pl-4">
    お気に入り登録数：
    <span class="font-semibold text-cyan-500"> <%= req.likes.count %></span>
    名
  </p>
</div>

app/views/shared/_modal_delete_account.html.erb
<div id="confirmationModal-<%= resource.id %>" class="hidden fixed inset-0 bg-gray-600 bg-opacity-75 overflow-y-auto h-full w-full">
  <div class="flex items-center justify-center min-h-screen">
    <div class="bg-white rounded-lg px-4 pt-5 pb-4 shadow-xl transform transition-all sm:max-w-lg sm:w-full">
      <div class="sm:flex sm:items-start">
        <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
          <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
            アカウントの退会
          </h3>
          <div class="mt-2">
            <p class="text-sm text-gray-500">
              アカウント情報が削除されます。本当に退会しますか？
            </p>
          </div>
        </div>
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <%= button_to '退会する', registration_path(resource_name), method: :delete, data: { confirm: 'アカウント情報が削除されます。本当に退会しますか？' }, class: 'w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm' %>
        <button data-close-modal="confirmationModal-<%= resource.id %>" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none sm:mt-0 sm:w-auto sm:text-sm">
          キャンセル
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_password_edit_form_fields.html.erb
<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f| %>
      <%= f.hidden_field :reset_password_token %>

      <div class="mb-8">
        <%= f.label :password, class: "block text-gray-700 text-base font-bold mb-2" do %>
          '新しいパスワード'
          <% if @minimum_password_length %>
            <em><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></em>
          <% end %>
        <% end %>
        <%= f.password_field :password, autocomplete: "new-password", class: form_field_error_class(resource, :password) %>
        <%= display_field_error_messages(resource, :password) %>
      </div>

      <div class="mb-8">
        <%= f.label :password_confirmation, 'パスワード（確認用）', class: "block text-gray-700 text-base font-bold mb-2" %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: form_field_error_class(resource, :password_confirmation) %>
        <%= display_field_error_messages(resource, :password_confirmation) %>
      </div>

      <%= f.submit '登録する', class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer mb-3' %>
    <% end %>

app/views/shared/_password_reset_form_field.html.erb
<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>

  <div class="mb-5">
    <%= f.label :email, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.email_field :email, autocomplete: "email", class: form_field_error_class(resource, :email)  %>
    <%= display_field_error_messages(resource, :email) %>
  </div>

  <%= f.submit 'パスワード再設定メールを送信', class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer mb-3' %>
<% end %>

app/views/shared/_registrations_edit_form_fields.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>

  <div class="mb-10">
    <%= f.label :email, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.email_field :email, autocomplete: "email", class: form_field_error_class(resource, :email) %>
    <%= display_field_error_messages(resource, :email) %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div><%= waiting_confirmation_for_email %></div>
  <% end %>

  <div class="mb-10">
    <%= f.label :current_password , class: "block text-gray-700 text-base font-bold mb-2" do %>
    現在のパスワード
    <% end %>
    <%= f.password_field :current_password, autocomplete: "current-password", class: form_field_error_class(resource, :current_password) %>
    <i class='text-sm text-gray-600'>※変更を反映するには現在のパスワードを入力してください</i>
    <%= display_field_error_messages(resource, :current_password) %>
  </div>

  <div class="mb-10">
    <%= f.label :password, class: "block text-gray-700 text-base font-bold mb-2" do %>
      新しいパスワード
      <em><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></em>
    <% end %>
    <%= f.password_field :password, autocomplete: "new-password", class: form_field_error_class(resource, :password) %>
    <% if @minimum_password_length %>
      <i class='text-sm text-gray-600'>※空欄のままなら変更されません</i>
    <% end %>
    <%= display_field_error_messages(resource, :password) %>
  </div>

  <div class="mb-6">
    <%= f.label :password_confirmation, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: form_field_error_class(resource, :password_confirmation) %>
    <%= display_field_error_messages(resource, :password_confirmation) %>
  </div>


  <div class="flex justify-between mb-16">
    <%= f.submit '更新', class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-12 rounded focus:outline-none focus:shadow-outline cursor-pointer' %>
    <%# buttunタグを使うとformが反応してputリクエストを送ってしまうため、spanタグ %>
    <span data-open-modal="confirmationModal-<%= resource.id %>" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-10 rounded focus:outline-none focus:shadow-outline cursor-pointer float-right">退会する</span>
  </div>
<% end %>
<%= render 'shared/modal_delete_account', resource_name: resource_name %>

app/views/shared/_registrations_form_fields.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

    <div class="mb-8">
      <%= f.label :email, class: "block text-gray-700 text-base font-bold mb-2" %>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: form_field_error_class(resource, :email) %>
      <%= display_field_error_messages(resource, :email) %>
    </div>

    <div class="mb-8">
      <%= f.label :password, class: "block text-gray-700 text-base font-bold mb-2" do %>
        <%= password %>
        <% if @minimum_password_length %>
          <em><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></em>
        <% end %>
      <% end %>
      <%= f.password_field :password, autocomplete: "new-password", class: form_field_error_class(resource, :password) %>
      <%= display_field_error_messages(resource, :password) %>

    </div>

    <div class="mb-8">
      <%= f.label :password_confirmation, class: "block text-gray-700 text-base font-bold mb-2" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: form_field_error_class(resource, :password_confirmation) %>
      <%= display_field_error_messages(resource, :password_confirmation) %>
    </div>

      <%= f.submit sign_up, class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer mb-3' %>
  <% end %>

app/views/shared/_requests_index.html.erb
<%# 一覧 %>
<div class="mb-12 shadow-lg rounded-lg overflow-hidden">
  <% @requests.each do |req| %>
    <div class="grid grid-cols-4 gap-4 border-b border-slate-200 p-4 hover:bg-sky-100 transition duration-150 ease-in-out last:border-b-0">
      <% if req.deadline_passed? %>
        <%= link_to public_request_path(req, back_url: back_url), class: "flex justify-center col-span-1" do %>
          <div class="bg-slate-500 rounded-lg text-white flex items-center justify-center h-24 w-24">
            <p class="text-center m-2">
              募集終了
            </p>
          </div>
        <% end %>
      <% else %>
        <%= link_to public_request_path(req, back_url: back_url), class: "flex justify-center col-span-1" do %>
          <div class="bg-cyan-500 rounded-lg text-white flex items-center justify-center h-24 w-24">
            <p class="text-center m-2">
              募集中<br>
              <%= "あと#{req.days_left}日" %>
            </p>
          </div>
        <% end %>
      <% end %>
      <div class="col-span-3 space-y-4">
        <%= link_to public_request_path(req, back_url: back_url) do %>
          <p class="font-bold text-xl text-blue-700 mb-2"><%= req.title %></p>
        <% end %>
        <p class="text-gray-600 pl-4">
          希望納期：<%= req.delivery_date.strftime("%Y年%m月%d日") %>
        </p>
        <div class="text-sm text-gray-500">
          <% if current_client && req.client == current_client %>
            <p class="pl-4">
              現在の応募者数　：
              <%= link_to clients_applicants_path(request_id: req.id) do %>
                <span class="font-semibold text-blue-700"><%= req.applicants.count %></span>
                名
              <% end %>
              <%= link_to clients_applicants_path(request_id: req.id) do %>
                <span class="font-semibold text-blue-700">（応募者一覧）</span>
              <% end %>
            </p>
          <% else %>
            <p class="pl-4">
              現在の応募者数　：
              <span class="font-semibold text-cyan-500"><%= req.applicants.count %></span>
              名
            </p>
          <% end %>
          <p class="pl-4">
            お気に入り登録数：
            <span class="font-semibold text-cyan-500"> <%= req.likes.count %></span>
            名
          </p>
        </div>
        <p class="text-right text-gray-400 text-xs mt-2">
          <%= req.client.name %>（<%= req.client.industry %>）
        </p>
      </div>
    </div>
  <% end %>
</div>
<%# ページネーション %>
<div class="flex justify-center">
  <%= paginate(@requests) %>
</div>

app/views/shared/_sessions_form_fields.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="mb-8">
    <%= f.label :email, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.email_field :email, autocomplete: "email", class: form_field_error_class(resource, :email) %>
  </div>
  <div class="mb-8">
    <%= f.label :password, class: "block text-gray-700 text-base font-bold mb-2" %>
    <%= f.password_field :password, autocomplete: "current-password", class: form_field_error_class(resource, :password) %>
  </div>
  <%= f.submit "#{user_type}ログイン", class: 'bg-blue-500 hover:bg-blue-700 text-white text-center font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer mb-3' %>
  <% if devise_mapping.rememberable? %>
    <div class="mb-8">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

<% end %>